### ISSUE TITLE
HTTP notifier headers

### ISSUE THREAD

**Issue by invernizzie** [Lowess/helm-charts#1]
Hi! Thank you for putting together these charts.

I'm interested in the Burrow one, but I need an addition—that I'm willing to contribute. In order to create alerts using Opsgenie's API, I need to set the `Authorization` header in notifier requests. This is possible by setting `notifier.<my-notifier>.headers`. In order to keep my API key secure, I'd use an env var loaded from a secret. Do you think this is a good approach?

Just to be sure, there's no way to set the headers option with the chart as it currently stands, or is there?

Also, you don't have a LICENSE file so could you please comment on whether I'm free to use this (and change it)?

**Comment by Lowess** [comment]
Hi @invernizzie , Thanks for your interest for this repository.

Can you please provide an example of Burrow configuration with the Opsgenie integration (blank out your api key) so that I have an idea of the content of the `notifier.<my-notifier>.headers` section ?

It looks like Burrow handles well configuration overrides using environment variables as per https://github.com/linkedin/Burrow/issues/486.

To implement the change I would recommend adding the `headers` section bellow https://github.com/Lowess/helm-charts/blob/master/charts/burrow/templates/burrow-configmap.yaml#L56 to handle non-sensitive headers. 

For sensitive data leverage environment variables and [Viper](https://github.com/spf13/viper#working-with-environment-variables).

Regarding the LICENSE. All charts from this repo are under [Apache2 license](https://github.com/Lowess/helm-charts/blob/master/charts/burrow/LICENSE) 

Feel free to submit a PR I will be happy to help you review it and get it released.

**Comment by invernizzie** [comment]
Thanks @Lowess, I will definitely add the `headers` field to the notifier section of the configmap.

The headers for Opsgenie would look like this:

```
[notifier.opsgenie]
  [notifier.opsgenie.headers]
  Authorization="GenieKey #redacted#"
  Accept="application/json"
```

I'm not sure if I'd be able to override a single header with and env var given that [burrow loads the headers section as a map](https://github.com/linkedin/Burrow/blob/master/core/internal/notifier/http.go#L205), but I'll try it out. Otherwise I'll use an env var for the whole section.

**Comment by Lowess** [comment]
You're right there is a good chance that you need to pass down all the headers as env var except if Viper does some merging logic when the two same keys are defined.
